name: Android CI

on: [push]

jobs:
  buils_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: |
        echo "API_KEY=test\nSHARED_SECRET=test" >> local.properties
        ./gradlew bundleDebug
        ./gradlew testDebugUnitTest
